### ISSUE TITLE
Centro seleccionado y cambiar especialidad

### ISSUE THREAD

**Issue by sio2sio2** [sio2sio2/lobaton#31]
Al cambiar de especialidad, queda seleccionado el centro en la barra lateral. Debería desaparecer por completo, si en la nueva especialidad no existe ese centro, o cambiar los datos si el centro sí existe. Haciendo uso de lo sugerido en #29, bastaría al cargar con hacer:

~~~~
g.cluster.seleccionado = centro
~~~~

y que centro sea ``null`` si el centro no existe en los nuevos datos.

**Comment by bermudoancio** [comment]
Hecho
