### ISSUE TITLE
Las correcciones no se desaplican

### ISSUE THREAD

**Issue by bermudoancio** [sio2sio2/lobaton#32]
Utilizando la interfaz visual (ocurre también utilizando la consola) se puede comprobar que si aplicamos una corrección (por ejemplo de adjudicaciones), posteriormente aplicamos otra de la misma sección, y desmarcamos una de las dos, éstas no serán desaplicadas. Al eliminarlas todas vuelve al estado normal debido a que la interfaz detecta que no hay ninguna seleccionada y llama al método desaplicar.
El funcionamiento correcto sería que cada vez que se llame al método de aplicar correcciones, se desapliquen, si estaban, las correcciones que no están en el nuevo array de parámetros

**Comment by sio2sio2** [comment]
Hecho.
