### ISSUE TITLE
Vacantes telefónicas en la interfaz virtual

### ISSUE THREAD

**Issue by sio2sio2** [sio2sio2/lobaton#38]
Las vacantes telefónicas en la interfaz visual se tratan como si fueran una adjudicación del proedimiento de modo que se muestra una leyenda absurda:

~~~~
(J) Interino: T.S. 0-0-0 (pet. ).
~~~~

Debería indicarse, simplemente: vacante telefónica.

Las vacantes telefónicas se caracterizar por tener una "pet"  (petición) igual a null

**Comment by bermudoancio** [comment]
Hecho. Ahora simplemente se muestra el texto "Vacante telefónica"
