### ISSUE TITLE
Mostrar toda la información de la oferta

### ISSUE THREAD

**Issue by bermudoancio** [sio2sio2/lobaton#63]
La parte de la información del centro referente a la oferta debe mostrar toda la información relacionada a ella, tal y como se describe en la [documentación](https://sio2sio2.github.io/lobaton/docs/html/03.dev/02.adjofer.html#datos). 
Además, cuando la oferta se encuentre filtrada, deberá mostrarse de alguna forma la(s) causa(s) por las que lo está.

**Comment by bermudoancio** [comment]
@sio2sio2 , recuérdame, ¿cuándo queda la oferta tachada? En principio lo he puesto así sólo cuando está extinta (ext a true) pero: ¿hay otras situaciones?

**Comment by sio2sio2** [comment]
@bermudoancio cuando la elimina una corrección. De hecho, acabo de caer en la cuenta de que no he tenido en cuenta eso de que hay enseñanzas que en realidad ya no existen (ext=true). Creo que la forma más elegante de solucionarlo es crear una corrección que sea eliminar enseñanzas extintas y aplicarla ocultamente siempre después de haber cargado los datos.

Abro tarea y mañana lo hago.

**Comment by sio2sio2** [comment]
@bermudoancio, cierro esta issue, porque está relacionada con #69, y te asigno aquella
