### ISSUE TITLE
Cambiar el sidebar por el plugin sidebar-v2

### ISSUE THREAD

**Issue by bermudoancio** [sio2sio2/lobaton#64]
Sería conveniente que la barra de información (sidebar) utilizada en la aplicación fuera la propuesta por el plugin https://github.com/nickpeihl/leaflet-sidebar-v2.

**Comment by sio2sio2** [comment]
Hay progresos. He logrado que la barra del _plugin_ incorpore un botón para enrollarse/desenrollarse, el botón de pantalla completa y la búsqueda de centros, con que he centralizado todo en ella (salvo el control +/- para el zoom que sigue en el mismo sitio y entiendo que es mejor que ahí esté). La búsqueda de centros he tenido que implementarla independientemente del plugin para barra de búsqueda que usaba, ya que este no se integraban bien en la barra. Funciona pero es probable que haya que darle un repaso al aspecto para mejorlarlo (quizás aplicándole bootstrap. Se puede consulltar cómo va quedando en esta prueba:

https://sio2sio2.github.io/lobaton/docs/examples/sidebar.html

Ya no se pueden colocar más iconos, porque de lo contrario no cabrán en un móvil apaisado.

Ahora voy, un poco a ciegas, a intentar integrar el selector de especialidad, las correcciones, ajustes e información de centro.

**Comment by sio2sio2** [comment]
Reabro, porque cerré por error y sólo debería cerrarse cuando, después de adaptar todo lo hecho, se hubiera completado la migración enla interfaz de vuejs.

**Comment by sio2sio2** [comment]
@bermudoancio , el retardo producido por ``v-model`` era más correoso de lo que pensaba. Lo he soslayado no usándolo, ya que de poco sirve tener el valor inmediato del ``input``. Lo que sí hay es un dato *especialidad* que almacena el valor de la especialidad, por si resulta útil.

Voy a darle un repaso al panel de búsqueda para reimplementarlo con vuejs. Está hecho con javascript a pelo. Si me lleva poco tiempo, me meto con el panel de correcciones.

**Comment by sio2sio2** [comment]
@bermudoancio,  Después del último commit (cdcf5c76f9ada16b8adb51e205fca36c0b94a82e), cierro esta tarea porque es un poco mastodóntica y separo lo que queda por hacer en tareas independientes.
