### ISSUE TITLE
Detalles visuales en la interfaz visual

### ISSUE THREAD

**Issue by sio2sio2** [sio2sio2/lobaton#68]
Hay que aplicarlo para que el aspecto sea presentable.

**Comment by sio2sio2** [comment]
@jbermudo He ido haciendo lo que he podido, pero quizás habría que darle un repasito.

**Comment by sio2sio2** [comment]
@bermudoancio. Cambio el título de la issue, porque la cosa ha quedado pasable. En esta tarea cabría impedir que dejende verse los iconos de la barra lateral o añadir la especialidad escogida en el panel de selección de especialidad.

**Comment by bermudoancio** [comment]
@sio2sio2 voy a subir una corrección para que todos los botones de la barra sean visibles siempre y no se monten unos sobre otros

**Comment by sio2sio2** [comment]
@bermudoancio Perfecto. Hay también que probar el selector de especialidades en un ipad/iphone. No estoy seguro de que funcione correctamente. Si no lo hace, habrá que usar un ``select`` normal para estos dispositivos. No sé si conoces a alguien que tenga uno.

**Comment by sio2sio2** [comment]
Cierro esto, porque ya se ha completado su propósito.
