### ISSUE TITLE
Panel de información de centro

### ISSUE THREAD

**Issue by sio2sio2** [sio2sio2/lobaton#69]
@bermudoancio, hay que trasladar esta información, que ya estaba creada en la antigua sidebar a la nueva.

**Comment by sio2sio2** [comment]
Al recomponer la interfaz, se ha incluido una opción *ocultarBorrado*, que se modifica a través de los ajustes, pensada para controlar si se quieren ver (tachadas) las enseñanzas y las adjudicaciones  desechadas, o si por el contrario no se quieren ver en absoluto. Habría que tenerlo en cuenta al hacer la migración.

**Comment by bermudoancio** [comment]
@sio2sio2 ¿La oferta que esté extinta debe seguir la misma regla de tachado/no visualización que las demás correcciones?

**Comment by sio2sio2** [comment]
Entiendo que sí. La única diferencia consiste en que son enseñanzas que jamás se verán sin tachar, porque la corrección se aplica automáticamente al cargar los datos y no hay forma a través de la interfaz de deshabilitarla.

**Comment by sio2sio2** [comment]
@bermudoancio  Acabo de generar nuevos json que incluyen las nuevas plantillas orgánicas para el curso 2019/2020.. Como los datos del procedimiento de colocación de efectivos se hacen basándose en las plantillas orgánicas del curso presente (2018/2019 en este caso), después de la publicación de las plantiillas orgánicas y hasta que no se resuelve el nuevo procedimiento de colocación, el json tiene dos datos de plantillas orgánicas para cada puesto "org" que contiene las plantillas antiguas y "norg" que contiene las nuevas. En los json antiguos sólo existía "org".

Como no sabías nada, es obvio que al mostrar la información de centro sólo están teniendo en cuenta "org", pero sería conveniente que también incluyeras "norg" (en caso de existir y si es distinto a "org") porque es un dato interesante: si la plantilla orgánica ha aumentado, entonces quizás disminuyan las plazas ofertadas en el procedimiento. En la plataforma antigua, lo que se hacía es poner el dato de la plantilla orgániza y al lado entre paréntesis el dato de la nueva. Si quieres verlo échale un vistazo a la antigua aplicación: pàra Informática el IES La Marisma de Huelva capital ha aumentado su plantilla orgánica del puesto 00590107 de 3 a 4. Como la de 11590107 no ha variado, sólo muestra un número.

**Comment by sio2sio2** [comment]
Hecho desde hace unos días.
