### ISSUE TITLE
Panel de solicitudes

### ISSUE THREAD

**Issue by sio2sio2** [sio2sio2/lobaton#80]
Sobra la base de lo hecho para la #79, puede hacerse un panel para crear la lista de peticiones de centros y localidades.

**Comment by bermudoancio** [comment]
@sio2sio2 Échale un vistazo a la rama listado. Tiene todos los cambios que dijimos. Si la ves bien, mezclamos con development

**Comment by sio2sio2** [comment]
@bermudoancio no he podido usarlo muchos, porque me acabo de desayunar con tu mensaje. ANtes de fusionar con development:

1. ¿No consideraste la posibilidad de habilitar/deshabilitar el modo solicitud al entrar en este panel/abrir otro? Con independencia de que haya un botón para controlarlo que sí lo veo necesario.
2. He probado a exportar el CSV y los códigos se guardan en formato numérico normal y no normalizado. Sería conveniente que se gaurdan en el normalizado porque ese es el que, si no recuerdo mal, exige luego la aplicación. Además, creo que debería ser el que se usase en la lista. En cuanto llegue al instituto miraré cuál es la función que normaliza, pero muy probablemente debería ser un getter de Centro. De manera que si haces centro.getData().codigo te devuelva el código normalizado. Te aviso cuando lo tenga.
3. Hay que comprobar antes si funciona bien el guardado del estado. He probado y no se conserva la lista. Muy probablemente porque me haya olvidado de cambiar el estado cuando se produce un evento reqyestchange. Pero esto es parte mía y debería verla yo.

Procuro hacer la aprte que me toca esta mañana y te digo.

**Comment by sio2sio2** [comment]
@bermudoancio  Hecho por mi parte. Puedes usar:

~~~~
centro.getData().codigo
~~~~

Para obtener el código normalizado del centro. Para las localidades también está definido.

**Comment by bermudoancio** [comment]
Rama listado mezclada a development
