### ISSUE TITLE
Filtrado por turnos de enseñanzas

### ISSUE THREAD

**Issue by acardograu** [sio2sio2/lobaton#84]
Un centro que tenga enseñanzas de mañana y tarde al aplicar el filtro con la opción de “elimina enseñanzas de mañana”, no puede obtenerse su resultado.
![DA57F766-B0A5-46AE-8C65-ADECB849735F](https://user-images.githubusercontent.com/25149015/58712905-c8a9aa80-83c1-11e9-9bc5-10651c86be48.jpeg)

**Comment by sio2sio2** [comment]
Corregido. El problema se debía a que  atendiendo a la literalidad lógica  "Eliminar enseñanzas de mañana" implica eliminar una enseñanza que se imparta mañana y tarde. Desde ese punto de vista, la aplicación actuaba correctamente. Pero eso no es lo que espera el usuario. Lo que espera el usuario es que el filtro más que "eliminar las enseñanzas de mañana", lo que haga es "conservar las enseñanzas de tarde". Así pues, ese ítem de turno ha pasado de aplicar la corrección así:

~~~~
Centro.filter("turno", {turno: 1});
~~~~

a aplicarla así:

~~~~
Centro.filter("turno", {turno: 2, inv: true});
~~~~

De paso se han cambiado los término que describen el turno a "mañana", "tarde" y "mañana y tarde".
