### ISSUE TITLE
Ampliar datos CSV exportado

### ISSUE THREAD

**Issue by nerotic** [sio2sio2/lobaton#94]
No veo ninguna configuracion en la app pero me gustaria poder exportar mis centros con el nombre de localidad y provincia incluido.

Hay forma de hacerlo?

**Comment by sio2sio2** [comment]
No, no hay forma. En realidad, el fichero de exportación/importación está pensado para poder guardar la lista de peticiones y cargarla posteriormente; o bien, para intercambiar la lista con la aplicación de la Junta. Para esa tarea basta exclusivamente con el código, e incluir el nombre de centro  se hizo por facilitar un poco la lectura a un humano de ese fichero, pero nada más.

**Comment by nerotic** [comment]
Hay alguna CSV descargable en alguna pagina de la Junta con estos datos?

**Comment by sio2sio2** [comment]
No, que yp sepa. Pero si tienes unos mínimos conocimientos de programación puedes generar el CSV que quieres, haciendo las mismas consultas que hace la aplicación web de la Junta para solicitar destinos. Si haces una consulta a la URL

~~~~~
http://www.juntadeandalucia.es/educacion/vscripts/Centros/Centro/getCentro.asp?codigo=04000018
~~~~~

se te devuelve una objeto json con las características del centro de código 04000018:

~~~~~
$ wget -qO - 'http://www.juntadeandalucia.es/educacion/vscripts/Centros/Centro/getCentro.asp?codigo=04000018'
[{"C_CODIGO":"04000018","D_ESPECIFICA":"Joaqu\u00EDn Tena Sicilia","D_DENOMINA":"Colegio de Educaci\u00F3n Infantil y Primaria","S_DENOMINA":"C.E.I.P.","D_TIPO":"P\u00FAblico","D_TITULAR":"Consejer\u00EDa de Educaci\u00F3n","C_NIF":"S4111001F","D_PROVINCIA":"Almer\u00EDa","D_MUNICIPIO":"Abla","D_LOCALIDAD":"Abla","D_DOMICILIO":"Paseo San Segundo,  7","C_POSTAL":"04510","T_CORREO_E":"04000018.edu@juntadeandalucia.es","N_TELEFONO":"950359901","N_FAX":"950359900","N_TELCORPOR":null,"T_PAGWEB":null,"N_COUTMX":519573.233750814,"N_COUTMY":4110525.37021993}]

**Comment by nerotic** [comment]
Gracias por el consejo, de hecho he sido programador asi que lo probare.
